[tool.coverage.run]
branch = true
source = ["generate_index"]

[tool.coverage.report]
skip_empty = true
show_missing = true
fail_under = 85
exclude_lines = [
    "if TYPE_CHECKING:",
    "pragma: no cover",
]

[tool.coverage.paths]
source = ["generate_index.py"]

[tool.ruff]
line-length = 88
target-version = "py39"
exclude = ["examples"]

[tool.ruff.lint]
select = ["A"]
ignore = []

[tool.pytest.ini_options]
addopts = "-ra --cov-config=pyproject.toml"
